// This file is auto-generated or manually created for Android builds.
// In desktop builds, this is typically generated by CMake from git information.
// For Android builds without full git context, these are stub values.

#pragma once

#define GIT_VERSION 1.0.0
#define GIT_BRANCH android
#define GIT_COMMITS 1
